name: Build package

on: [ push, pull_request, workflow_dispatch ]

jobs:
  build_pkg:
    runs-on: ubuntu-20.04
    steps:

    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 1

    - name: Checkout dbglogger
      uses: actions/checkout@v3
      with:
        repository: bucanero/dbglogger
        path: dbglogger

    - name: Checkout zip
      uses: actions/checkout@v3
      with:
        repository: bucanero/zip
        path: zip

    - name: Checkout oosdk_libraries
      uses: actions/checkout@v3
      with:
        repository: bucanero/oosdk_libraries
        path: oosdk_libraries

    - name: Checkout SDL-PS4
      uses: actions/checkout@v3
      with:
        repository: bucanero/SDL-PS4
        path: SDL-PS4
        ref: ps4

    - name: Checkout mxml
      uses: actions/checkout@v3
      with:
        repository: bucanero/mxml
        path: mxml

    - name: Checkout cJSON
      uses: actions/checkout@v3
      with:
        repository: bucanero/cJSON
        path: cJSON

    - name: Checkout libjbc
      uses: actions/checkout@v3
      with:
        repository: bucanero/ps4-libjbc
        path: ps4-libjbc

    - name: Checkout Cheat repository
      uses: actions/checkout@v3
      with:
        repository: GoldHEN/GoldHEN_Cheat_Repository
        path: cheats

    - name: Checkout Patch repository
      uses: actions/checkout@v3
      with:
        repository: GoldHEN/GoldHEN_Patch_Repository
        path: appdata1
        ref: gh-pages

    - name: Set env vars
      run: |
        ver="1.$(git rev-list HEAD --count)"
        echo "commit_ver=$ver" >> $GITHUB_ENV
        echo "pkg_file=IV0000-GOLD00777_00-GOLDCHEATS000PS4.pkg" >> $GITHUB_ENV
        echo "llvm_ver=12.0" >> $GITHUB_ENV

      # temporary release until 0.53 is released
    - name: Download OpenOrbis Toolchain
      run: |
        curl -sL https://github.com/illusion0001/OpenOrbis-PS4-Toolchain/releases/download/0.0.1.416/toolchain.tar.gz | tar xvz -C ./
        echo "OO_PS4_TOOLCHAIN=${GITHUB_WORKSPACE}/OpenOrbis/PS4Toolchain" >> $GITHUB_ENV
        cp oosdk_libraries/build_rules.mk OpenOrbis/PS4Toolchain/build_rules.mk

    - name: Cache LLVM and Clang
      id: cache-llvm
      uses: actions/cache@v3
      with:
        path: ./llvm
        key: llvm-${{ env.llvm_ver }}

    - name: Install LLVM and Clang
      uses: KyleMayes/install-llvm-action@v1
      with:
        version: ${{ env.llvm_ver }}
        cached: ${{ steps.cache-llvm.outputs.cache-hit }}

    - name: Install zlib
      working-directory: oosdk_libraries/zlib_partial
      run: |
        make install

    - name: Install polarssl
      working-directory: oosdk_libraries/polarssl-1.3.9
      run: |
        make install

    - name: Install zip
      working-directory: zip
      run: |
        make install

    - name: Install dbglogger
      working-directory: dbglogger
      run: |
        make -f Makefile.PS4 install

    - name: Install mini xml
      working-directory: mxml/ps4
      run: |
        make install

    - name: Install cjson
      working-directory: cJSON/ps4
      run: |
        make install

    - name: Install libjbc
      working-directory: ps4-libjbc
      run: |
        make install

    - name: Install SDL2 library
      working-directory: SDL-PS4
      run: |
        mkdir orbis && cd orbis
        cmake --toolchain ../cmake/openorbis.cmake ..
        make
        cp libSDL2.a "${OO_PS4_TOOLCHAIN}/lib"

    - name: Install libcurl library
      working-directory: oosdk_libraries/curl-7.64.1
      run: |
        mkdir orbis && cd orbis
        cmake --toolchain ../../../SDL-PS4/cmake/openorbis.cmake .. -DCMAKE_USE_POLARSSL=1 -DUSE_UNIX_SOCKETS=0 -DENABLE_THREADED_RESOLVER=0 -DENABLE_IPV6=0
        make libcurl
        cp lib/libcurl.a "${OO_PS4_TOOLCHAIN}/lib"
        cp -R ../include/curl "${OO_PS4_TOOLCHAIN}/include/"

    - name: Build Gold Cheats App Package
      run: |
        unzip appdata1/patch1.zip
        make createzip
        make

    - name: Push package artifact
      uses: actions/upload-artifact@v3
      with:
        name: goldcheats-build_${{ env.commit_ver }}
        path: ${{ env.pkg_file }}
        if-no-files-found: error
        retention-days: 7 # don't keep artifacts for too long
